### ISSUE TITLE
bug: DefinitionManager is broken

### ISSUE THREAD

**Issue by buracc** [unethicalite/unethicalite#137]
Bug submitted by: C17#8747 (296968385672249344)

2022-07-14 17:41:20:371 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber java.lang.NullPointerException: Cannot read the array length because "<local2>" is null     at kb.getStaticChildren(Widget.java:415)     at net.unethicalite.client.managers.DefinitionManager.checkWidget(DefinitionManager.java:366)     at net.unethicalite.client.managers.DefinitionManager.onWidgetHiddenChanged(DefinitionManager.java:215)     at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)     at net.runelite.client.eventbus.EventBus.post(EventBus.java:220)     at net.runelite.client.util.DeferredEventBus.replay(DeferredEventBus.java:69)     at net.unethicalite.client.minimal.MinimalHooks.tick(MinimalHooks.java:190)     at client.doCycle(Client.java:2862)     at client.ab(Client.java)     at ap.o(GameEngine.java:338)     at ap.run(GameEngine.java:317)     at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by buracc** [comment]
fixed
