### ISSUE TITLE
Vanilla spoof

### ISSUE THREAD

**Issue by 7upSprite** [unethicalite/unethicalite#185]
Vanilla spoof starting via cli, picture attached. If Error loading RS occurs, is it possible to switch worlds and try again? 

2022-07-25 14:54:23:725 [Preloader] DEBUG net.runelite.client.rs.ClientLoader - error downloading backup config
java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocksSocketImpl.readSocksReply(SocksSocketImpl.java:137)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:455)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at net.runelite.client.rs.ClientConfigLoader.fetch(ClientConfigLoader.java:51)
	at net.runelite.client.rs.ClientLoader.downloadFallbackConfig(ClientLoader.java:260)
	at net.runelite.client.rs.ClientLoader.downloadConfig(ClientLoader.java:248)
	at net.runelite.client.rs.ClientLoader.doLoad(ClientLoader.java:132)
	at net.runelite.client.rs.ClientLoader.get(ClientLoader.java:112)
	at net.unethicalite.client.minimal.MinimalClient.lambda$main$1(MinimalClient.java:252)
	at java.base/java.lang.Thread.run(Thread.java:829)

2022-07-25 14:54:23:726 [Preloader] ERROR net.runelite.client.rs.ClientLoader - Error loading RS!
java.net.UnknownHostException: oldschool9.runescape.com:443
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:462)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at net.runelite.client.rs.ClientConfigLoader.fetch(ClientConfigLoader.java:51)
	at net.runelite.client.rs.ClientLoader.downloadConfig(ClientLoader.java:215)
	at net.runelite.client.rs.ClientLoader.doLoad(ClientLoader.java:132)
	at net.runelite.client.rs.ClientLoader.get(ClientLoader.java:112)
	at net.unethicalite.client.minimal.MinimalClient.lambda$main$1(MinimalClient.java:252)
	at java.base/java.lang.Thread.run(Thread.java:829)

2022-07-25 14:54:23:761 [Preloader] ERROR n.u.client.minimal.MinimalClient - Uncaught exception:
java.lang.RuntimeException: java.net.UnknownHostException: oldschool9.runescape.com:443
	at net.runelite.client.rs.ClientLoader.get(ClientLoader.java:117)
	at net.unethicalite.client.minimal.MinimalClient.lambda$main$1(MinimalClient.java:252)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.UnknownHostException: oldschool9.runescape.com:443
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:462)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at net.runelite.client.rs.ClientConfigLoader.fetch(ClientConfigLoader.java:51)
	at net.runelite.client.rs.ClientLoader.downloadConfig(ClientLoader.java:215)
	at net.runelite.client.rs.ClientLoader.doLoad(ClientLoader.java:132)
	at net.runelite.client.rs.ClientLoader.get(ClientLoader.java:112)
	... 2 common frames omitted

![Capture](https://user-images.githubusercontent.com/48745305/180798215-2670ce6b-910e-45ef-b59c-e797e6b96da9.PNG)

**Comment by 7upSprite** [comment]
Can confirm proxy works because I launched another client 5 seconds afterwards using same proxy and it was able to load into that world.

**Comment by 7upSprite** [comment]
![Capture](https://user-images.githubusercontent.com/48745305/180801199-2e6473f9-10bb-41a1-a77f-21fe32ee1438.PNG)

**Comment by 7upSprite** [comment]
Also getting Malformed Login Packet when trying to login
