### ISSUE TITLE
bug: ObjectPackets.useItemOnTileObject results in connection lost

### ISSUE THREAD

**Issue by Vitalflea** [unethicalite/unethicalite#236]
**Describe the bug**
using ObjectPackets.useItemOnTileObject results in connection lost

**Additional context**
`
2022-08-24 12:17:33:765 [pool-7-thread-1] ERROR n.u.api.plugins.LoopedPlugin - Error in loop
java.lang.AssertionError: null
	at jg.send(PacketBufferNode.java:19)
	at net.unethicalite.api.packets.ObjectPackets.queueItemUseOnTileObjectPacket(ObjectPackets.java:89)
	at net.unethicalite.api.packets.ObjectPackets.useItemOnTileObject(ObjectPackets.java:84)
	at dev.vital.prayer.VitalPrayer.loop(VitalPrayer.java:62)
	at net.unethicalite.api.plugins.LoopedPlugin.lambda$loopTask$1(LoopedPlugin.java:70)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)`

**Comment by yuri-moens** [comment]
`    final Item item = Inventory.getFirst("Potato cactus");
    final TileObject chest = TileObjects.getNearest("Bank chest");
    GameThread.invoke(() -> ObjectPackets.useItemOnTileObject(item, chest));`

Works for me. Are you using the latest version and running it on the game thread?

**Comment by buracc** [comment]
Possibly related to the X coordinates being bugged, which has been resolved in the latest commit. Make sure you're up to date
